Repository openid/OpenID4VP, pull requests merged in 2025-02, with the labels that each got.

#412 Fix erroneous client ID scheme `x505_san_dns` in request example
  examples/request/request.txt
Labels: editorial

#410 clarify when authorization_signed_response_alg is omitted, do not sign
  openid-4-verifiable-presentations-1_0.md
Labels: has-PR

#380 discuss the use of apu/apv in the JWE header of OpenID4VP encrypted responses
  openid-4-verifiable-presentations-1_0.md
Labels: ISO_VirtualMeeting

#426 Editorial: Update notices section
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#427 Editorial: Update change controller for IANA entries
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#428 Editorial: Request Object/URI definitions are from JAR RFC
  openid-4-verifiable-presentations-1_0.md
Labels: editorial
