Repository openid/OpenID4VP, pull requests merged in 2025-05, with the labels that each got.

#583 Add IANA considerations for encrypted_response_enc_values_supported
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#582 Remove now unused reference to JARM spec
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#588 Move verifier_attestations IANA consideration to correct section
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#536 add example of response encryption
  openid-4-verifiable-presentations-1_0.md
Labels: post-wglc-is-ok

#607 Add Matthew Miller to Acknowledgements - May 2025
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#611 add few more missing contributors that we know have CA
  openid-4-verifiable-presentations-1_0.md
Labels: editorial, editors

#618 Editorial: Fix type_values example for W3C VC
  openid-4-verifiable-presentations-1_0.md
Labels: editorial
