Repository openid/OpenID4VP, pull requests merged in 2025-04, with the labels that each got.

#421 Make transaction data credential format specific and define details for sd-jwt and mdoc
  openid-4-verifiable-presentations-1_0.md
Labels: priority, transaction data, EUDIW

#498 Correct text describing an example request object payload
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#507 Describe nonce for AnonCreds
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#514 make type_values to use expanded type values
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#480 Make doctype_value and vct_values mandatory
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#497 update changelog to -26
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#516 change openid_fed to openid_federation for Trusted Authorities Query
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#485 note on pre-final specs
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#499 Clarify iss value in Request Object (JAR)
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#517 add identifier for JWS JSON Serialized multi RP requests
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#492 Change processing rules to allow same credential fulfilling different queries
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#482 add verifier_attestations parameter to authz req
  openid-4-verifiable-presentations-1_0.md
Labels: editors

#540 Add missing entries into Document History
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#538 Specifies value matching for mdocs via a reference to cbor-to-json
  openid-4-verifiable-presentations-1_0.md
Labels: during-wglc

#550 Update Digital Credentials API reference link (post WG migration)
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#500 revamp vp formats
  examples/client_metadata/mso_mdoc_verifier_metadata.json
  examples/client_metadata/sd_jwt_vc_verifier_metadata.json
  examples/client_metadata/w3c_jwt_verifier_metadata.json
  examples/client_metadata/w3c_ldp_verifier_metadata.json
  examples/credentials/ldp_vc.json
  examples/request/request_object_client_id_did.json
  examples/response/ldp_vc.json
  openid-4-verifiable-presentations-1_0.md
Labels: during-wglc

#557 Consistently use the term 'Client Identifier Prefix'
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#559 Explicitly reference figures by their number
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#558 Replace uses of 'Relying Party' with 'Verifier'
  openid-4-verifiable-presentations-1_0.md
Labels: editorial

#564 Remove some no longer used examples
  examples/credentials/ac_vc.json
  examples/request/request.txt
  examples/response/ac_vp_sd.json
  examples/response/jarm_jwt_vc_json_body.json
Labels: editorial

#459 add sd-jwt vcld
  examples/sd_jwt_vcld/01/disclosures.md
  examples/sd_jwt_vcld/01/kb_jwt_header.json
  examples/sd_jwt_vcld/01/kb_jwt_payload.json
  examples/sd_jwt_vcld/01/kb_jwt_serialized.txt
  examples/sd_jwt_vcld/01/sd_jwt_issuance.txt
  examples/sd_jwt_vcld/01/sd_jwt_jws_part.txt
  examples/sd_jwt_vcld/01/sd_jwt_payload.json
  examples/sd_jwt_vcld/01/sd_jwt_presentation.txt
  examples/sd_jwt_vcld/01/specification.yml
  examples/sd_jwt_vcld/01/user_claims.json
  examples/sd_jwt_vcld/01/verified_contents.json
  examples/sd_jwt_vcld/README.md
  examples/sd_jwt_vcld/settings.yml
  openid-4-verifiable-presentations-1_0.md
Labels: during-wglc

#565 Remove jwt_vp_json from some examples
  openid-4-verifiable-presentations-1_0.md
Labels: editorial, post-wglc-is-ok

#554 clarify client id prefix processing
  openid-4-verifiable-presentations-1_0.md
Labels: post-wglc-is-ok

#465 Improvements regarding DC API
  openid-4-verifiable-presentations-1_0.md
Labels: editorial, editors, during-wglc, post-wglc-is-ok
